# Generated by Django 3.2.15 on 2022-12-15 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0003_post_file_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='file_upload',
            field=models.FileField(blank=True, upload_to='room/files/%Y/%m/%d/'),
        ),
    ]
